- name: Valida si el puerto está cerrado.
    tags: amvalidate1
    wait_for:
        host: "{{inventory_hostname}}"
        port: "{{webserver_port}}"
        delay: 10
        timeout: 30
        state: stopped
        msg: "El puerto del WebServer todavía no está cerrado"
    when: ansible_hostname == "{{inventory_hostname}}"
    register: amvalidate1
    ignore_errors: true
