- name: Unir los workers
  hosts: workers
  become: yes
  gather_facts: yes

  tasks:
   - name: Copia el comando join command desde Ansiblehost a los nodos worker
     become: yes
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: Une los nodos Worker al cluster.
     become: yes
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not